#!/bin/bash

# OpenShare
# Copyright (C) 2026 Ace Jones / ATech
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


CLEAN=false
RUN=false

for arg in "$@"; do
  case "$arg" in
    -c) CLEAN=true ;;
    -r)   RUN=true ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

if $CLEAN; then
  rm -rf build
fi

mkdir -p build

cmake -S . -B build
cmake --build build

if $RUN; then
  ./build/OpenShare
fi
